# Generated by Django 5.0.7 on 2024-07-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qna", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
