# Generated by Django 5.0.7 on 2024-07-29 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qna", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="is_faq",
            new_name="isfaq",
        ),
    ]
