# Generated by Django 5.0.7 on 2024-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qna", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="password",
            field=models.PositiveBigIntegerField(),
        ),
    ]
