# Generated by Django 5.0.7 on 2024-08-03 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("single_page", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="company",
            new_name="company_name",
        ),
    ]
