# Generated by Django 5.0.7 on 2024-07-27 01:51

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=1, null=True)),
                ("company", models.CharField(max_length=10, null=True, unique=True)),
                ("com_num", models.CharField(blank=True, max_length=14, null=True)),
                ("address_num", models.CharField(blank=True, max_length=5, null=True)),
                ("address_info", models.TextField(blank=True, null=True)),
                ("address_detail", models.TextField(blank=True, null=True)),
                ("recent_apply", models.DateTimeField(auto_now=True, null=True)),
                ("recent_employee", models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DoneApply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=10, null=True)),
                ("applicant", models.CharField(max_length=10, null=True)),
                ("apcan_phone", models.CharField(max_length=14, null=True)),
                ("done_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=10, null=True)),
                (
                    "recent_address_num",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("recent_address_info", models.TextField(blank=True, null=True)),
                ("recent_address_detail", models.TextField(blank=True, null=True)),
                ("recent_deli_request", models.TextField(blank=True, null=True)),
                ("recent_company", models.CharField(max_length=10, null=True)),
                ("recent_num", models.CharField(max_length=14, null=True, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apply_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("company", models.CharField(max_length=10, null=True)),
                ("com_num", models.CharField(blank=True, max_length=14, null=True)),
                ("address_num", models.CharField(blank=True, max_length=5, null=True)),
                ("address_info", models.TextField(blank=True, null=True)),
                ("address_detail", models.TextField(blank=True, null=True)),
                ("deli_request", models.TextField(blank=True, null=True)),
                ("applicant", models.CharField(max_length=10, null=True)),
                (
                    "apcan_phone",
                    models.CharField(max_length=14, null=True, unique=True),
                ),
                (
                    "progress",
                    models.CharField(
                        choices=[
                            (0, "박스 요청중"),
                            (1, "박스 전송중"),
                            (2, "박스 수거 요청중"),
                            (3, "수거진행중"),
                        ],
                        default=0,
                        max_length=2,
                        null=True,
                    ),
                ),
                ("box_num", models.IntegerField(null=True)),
                ("invoice_numberaddress_num", models.TextField(null=True)),
                ("zir_block_count", models.IntegerField(blank=True, null=True)),
                ("zir_powder_count", models.IntegerField(blank=True, null=True)),
                ("round_bar_count", models.IntegerField(blank=True, null=True)),
                ("tool_count", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
