# Generated by Django 5.0.7 on 2024-08-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_apply", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
