# Generated by Django 5.0.7 on 2024-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='resent_apply',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='company_info',
            name='resent_employee',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
