# Generated by Django 4.1 on 2024-07-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box_apply',
            name='address_num',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
