# Generated by Django 5.0.7 on 2024-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_apply", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="com_num",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
