# Generated by Django 5.0.7 on 2024-07-27 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manage_apply", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
