# Generated by Django 5.0.7 on 2024-08-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneapply',
            name='box_num',
            field=models.IntegerField(null=True),
        ),
    ]
