# Generated by Django 4.1 on 2024-07-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='company',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
