# Generated by Django 5.0.7 on 2024-08-03 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manage_apply", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apply",
            name="user",
        ),
    ]
