# Generated by Django 5.0.7 on 2024-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apply', '0002_doneapply_box_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='sent_box_num',
            field=models.IntegerField(null=True),
        ),
    ]
