# Generated by Django 5.0.7 on 2024-07-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apply', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='progress',
            field=models.IntegerField(choices=[(0, '박스 요청중'), (1, '박스 전송중'), (2, '박스 수거 요청중'), (3, '수거진행중')], default=0, max_length=2, null=True),
        ),
    ]
