# Generated by Django 4.1 on 2024-07-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apply', '0002_alter_box_apply_address_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box_apply',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='box_apply',
            name='pickup_apply',
        ),
        migrations.RemoveField(
            model_name='box_apply',
            name='pickup_ing',
        ),
        migrations.RemoveField(
            model_name='box_apply',
            name='send_box',
        ),
    ]
