# Generated by Django 5.0.7 on 2024-07-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apply', '0002_company_info_resent_apply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='resent_apply',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
