# Generated by Django 4.1 on 2024-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apply', '0003_remove_box_apply_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box_apply',
            name='progress',
            field=models.CharField(choices=[('0', '박스 요청중'), ('1', '박스 전송중'), ('2', '박스 수거 요청중'), ('3', '수거진행중'), ('4', '수거완료')], default='0', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='box_apply',
            name='invoice_numberaddress_num',
            field=models.TextField(null=True),
        ),
    ]
