# Generated by Django 5.0.7 on 2024-07-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apply', '0003_alter_company_info_resent_apply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='get_num',
        ),
        migrations.AlterField(
            model_name='apply',
            name='address_num',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='company',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='address_num',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
