# Generated by Django 4.1 on 2024-07-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apply', '0004_box_apply_progress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='box_apply',
            new_name='apply',
        ),
    ]
