# Generated by Django 5.0.7 on 2024-07-27 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manage_apply", "0004_alter_apply_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apply",
            old_name="invoice_numberaddress_num",
            new_name="invoice_num",
        ),
    ]
