# Generated by Django 5.0.7 on 2024-08-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManageApplyCompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                ("company", models.CharField(max_length=10)),
                ("com_num", models.CharField(max_length=14)),
                ("address_num", models.CharField(max_length=5)),
                ("address_info", models.TextField()),
                ("address_detail", models.TextField()),
                ("recent_apply", models.DateTimeField()),
                ("recent_employee", models.CharField(max_length=10)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "db_table": "manage_apply_companyinfo",
                "managed": False,
            },
        ),
    ]
